### ISSUE TITLE
Naam migratie is dubbel

### ISSUE THREAD

**Issue by jeromy97** [Darkashli/izi#1]
Deze error krijg ik nog vóórdat ik aan het testplan ben begonnen.
Tijdens het aanroepen van /migrate.

De naam van de migratie is dubbel.
![Dubbele migratie naam](https://user-images.githubusercontent.com/17589613/64701713-9708ab00-d4a9-11e9-8e65-7236c65ccdc1.png)

Gevonden door Jeromy Hettinga 06-09-2019

**Comment by Darkashli** [comment]
9-11-2019
release v1 
Ik heb de migratie file _status aangepast + recente branche met Test branche gemigreerd.

**Comment by Darkashli** [comment]
solved by renaming migration
