### ISSUE TITLE
Dubbele kolom naam in Business tabel

### ISSUE THREAD

**Issue by jeromy97** [Darkashli/izi#2]
Bij de tweede test krijg ik een foutmelding op de migratie (gevonden: release 0, opgelost: release 1)
 
De kolom “Status” die je probeert toe te voegen in application\migrations\20190902152300_status.php bestaat inderdaad al.
Dit mag je nog even aanpassen voordat ik verder kan testen.
![Dubbele kolom naam](https://user-images.githubusercontent.com/17589613/64702113-3e85dd80-d4aa-11e9-9a2c-009fba87e817.png)

Gevonden door Jeromy Hettinga 09-09-2019

**Comment by Darkashli** [comment]
release v1

De column "Status" die in  application\migrations\20190902152300_status.php is, wordt aangepast naar "CurrentSituationAndAdvice" en migratie naam wordt nu" _current_situation_and_adavice".

Opgelost door Alaa Darkashli 09-09-2019

**Comment by jeromy97** [comment]
2e tets is geslaagd (zie: testplan hieronder):

[i-1-f-2 (ingevuld door Jeromy) (2).xlsx](https://github.com/Darkashli/izi/files/3604083/i-1-f-2.ingevuld.door.Jeromy.2.xlsx)

Ik zie alleen dat de bestanden zelf in het mapje "conditions_general" worden opgeslagen maar dat is weer een andere issue denk ik ;)
