### ISSUE TITLE
Dubbele kolom naam in Quotation tabel (gevonden: release 0, opgelost: release 1)

### ISSUE THREAD

**Issue by jeromy97** [Darkashli/izi#3]
Bij het opslaan van de condities worden de teksten wel opgeslagen maar de PDF kolommen blijven leeg.

Bijgevoegd het testplan die ik gevolgd heb.

[Kopie van i-1-f-2 (ingevuld door Jeromy).xlsx](https://github.com/Darkashli/izi/files/3601063/Kopie.van.i-1-f-2.ingevuld.door.Jeromy.xlsx)

Gevonden door Jeromy Hettinga 11-09-2019

**Comment by Darkashli** [comment]
bug gevonden in: codereview vooraf aan iteratie 1 (dev branche)
In de Sittings controller->index function->op lijn 131 (if statement) wordt aangepast

Bug opgelost in release 1 door Alaa darkashli 11-09-2019
