### ISSUE TITLE
Dynamisch pad naar upload (gevonden: release v1, opgelost: release v2)

### ISSUE THREAD

**Issue by jeromy97** [Darkashli/izi#5]
Wanneer je een handtekening uploadt moet deze in het mapje van het bedrijf komen te staan maar dit lijkt nog niet goed te werken.

Gevonden door Jeromy Hettinga 27-09-2019

**Comment by Darkashli** [comment]
bug gevonden in: codereview vooraf aan iteratie 2 (dev branche)

Bug opgelost in release v2 door Alaa Darkashli 27-09-2019
